generate_error_reason: NO_VALID_GIT_FOUND
